name: Badges

on:
  push:
    branches: [ main ]

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install coverage-badge

    - name: Run tests with coverage
      run: |
        pytest --cov=src --cov-report=term

    - name: Generate coverage badge
      run: |
        coverage-badge -o coverage.svg -f

    - name: Commit badge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add coverage.svg || true
        git commit -m "chore: Update coverage badge" || true
        git push || true
