name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black ruff mypy

    - name: Check code formatting with Black
      run: |
        black --check src/ tests/ || true

    - name: Lint with Ruff
      run: |
        ruff check src/ tests/ || true

    - name: Type check with mypy
      continue-on-error: true
      run: |
        mypy src/ --ignore-missing-imports || true